<?php
if (!defined('PD_APP')) { define('PD_APP', true); } // bezpośrednio (Apache) lub przez dispatcher w index.php (nginx)
$page = 'galeria';
$title = 'Galeria: laweta w akcji | Pomoc Drogowa Pabianice';
$desc = 'Zdjęcia z realizacji: holowanie, transport pojazdów i pomoc na trasie w Pabianicach i okolicy. Pomoc Drogowa Łukasz Rogowski — zadzwoń 24/7: +48 517 574 330.';
$path = '/galeria/';
$preloadHero = false; // galeria nie ma obrazu hero na stronie (og:image = zdjęcie roli galeria-hero)
$pageJs = 'assets/js/galeria.js';
include __DIR__ . '/partials/config.php';
$ogImage = 'assets/img/hero/' . pd_slug('galeria-hero') . '.jpg';
include __DIR__ . '/partials/head.php';
include __DIR__ . '/partials/header.php';
?>
  <!-- NAGŁÓWEK -->
  <section id="top" style="background:#141414;border-bottom:1px solid #333;scroll-margin-top:var(--navh)">
    <div style="max-width:1200px;margin:0 auto;padding:clamp(48px,8vw,72px) 20px clamp(36px,6vw,48px);display:flex;justify-content:space-between;align-items:flex-end;gap:24px;flex-wrap:wrap">
      <div style="display:flex;flex-direction:column;gap:16px;max-width:640px">
        <nav aria-label="Okruszki" style="font-size:14px;color:#aaa"><a href="/" style="color:#aaa">Strona główna</a> <span style="color:#666">/</span> <span style="color:#f5c518">Galeria</span></nav>
        <h1 style="margin:0;font-family:'Barlow Condensed';font-weight:800;font-size:clamp(44px,7vw,80px);line-height:.95">Galeria realizacji</h1>
        <p style="margin:0;font-size:18px;line-height:1.55;color:#ccc;text-wrap:pretty">Laweta w akcji — holowania, transporty i pomoc na trasie w Pabianicach i okolicy. Kliknij zdjęcie, żeby je powiększyć.</p>
      </div>
      <a href="<?php echo $GMAPS_PLACE; ?>" target="_blank" rel="noopener" class="hov-brand hov-lift-flat" style="border:2px solid #f5c518;color:#f5c518;font-weight:700;padding:12px 18px;font-size:15px;transition:background-color .2s,color .2s,transform .2s">Więcej zdjęć w wizytówce Google →</a>
    </div>
  </section>
  <div style="height:16px;background:repeating-linear-gradient(135deg,#f5c518 0 22px,#111 22px 44px)"></div>

  <!-- ZDJĘCIA (kafelki generuje tools/build_gallery.py) -->
  <section id="zdjecia" aria-label="Zdjęcia z realizacji" style="max-width:1200px;margin:0 auto;padding:clamp(32px,6vw,56px) 20px clamp(52px,9vw,80px);scroll-margin-top:var(--navh)">
    <div class="gal-grid">
<!-- GALLERY:START -->
      <button type="button" class="gal-cell is-big" data-shot="0" data-full="/assets/img/zolta-laweta-z-autem-na-parkingu-pabianice.jpg" aria-label="Powiększ zdjęcie: Żółta laweta z samochodem kombi na parkingu — Pomoc Drogowa Łukasz Rogowski">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/zolta-laweta-z-autem-na-parkingu-pabianice-400.avif 400w, /assets/img/thumbs/zolta-laweta-z-autem-na-parkingu-pabianice-800.avif 800w" sizes="(max-width:699px) 100vw, 50vw"><source type="image/webp" srcset="/assets/img/thumbs/zolta-laweta-z-autem-na-parkingu-pabianice-400.webp 400w, /assets/img/thumbs/zolta-laweta-z-autem-na-parkingu-pabianice-800.webp 800w" sizes="(max-width:699px) 100vw, 50vw"><img src="/assets/img/thumbs/zolta-laweta-z-autem-na-parkingu-pabianice.jpg" alt="Żółta laweta z samochodem kombi na parkingu — Pomoc Drogowa Łukasz Rogowski" width="800" height="450" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell" data-shot="1" data-full="/assets/img/auto-zastepcze-audi-pabianice.jpg" aria-label="Powiększ zdjęcie: Samochód zastępczy Audi A4 dla poszkodowanego z OC sprawcy — Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/auto-zastepcze-audi-pabianice-400.avif 400w, /assets/img/thumbs/auto-zastepcze-audi-pabianice-800.avif 800w" sizes="(max-width:699px) 50vw, 25vw"><source type="image/webp" srcset="/assets/img/thumbs/auto-zastepcze-audi-pabianice-400.webp 400w, /assets/img/thumbs/auto-zastepcze-audi-pabianice-800.webp 800w" sizes="(max-width:699px) 50vw, 25vw"><img src="/assets/img/thumbs/auto-zastepcze-audi-pabianice.jpg" alt="Samochód zastępczy Audi A4 dla poszkodowanego z OC sprawcy — Pabianice" width="800" height="450" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell" data-shot="2" data-full="/assets/img/awaryjne-odpalanie-autobusu-mobilny-serwis-pabianice.jpg" aria-label="Powiększ zdjęcie: Mobilny serwis Pomocy Drogowej przy autobusie z rozładowanym akumulatorem — Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/awaryjne-odpalanie-autobusu-mobilny-serwis-pabianice-400.avif 400w, /assets/img/thumbs/awaryjne-odpalanie-autobusu-mobilny-serwis-pabianice-800.avif 800w" sizes="(max-width:699px) 50vw, 25vw"><source type="image/webp" srcset="/assets/img/thumbs/awaryjne-odpalanie-autobusu-mobilny-serwis-pabianice-400.webp 400w, /assets/img/thumbs/awaryjne-odpalanie-autobusu-mobilny-serwis-pabianice-800.webp 800w" sizes="(max-width:699px) 50vw, 25vw"><img src="/assets/img/thumbs/awaryjne-odpalanie-autobusu-mobilny-serwis-pabianice.jpg" alt="Mobilny serwis Pomocy Drogowej przy autobusie z rozładowanym akumulatorem — Pabianice" width="800" height="450" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell" data-shot="3" data-full="/assets/img/transport-quada-na-lawecie-pabianice.jpg" aria-label="Powiększ zdjęcie: Transport quada na lawecie — Pomoc Drogowa Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/transport-quada-na-lawecie-pabianice-400.avif 400w, /assets/img/thumbs/transport-quada-na-lawecie-pabianice-800.avif 800w" sizes="(max-width:699px) 50vw, 25vw"><source type="image/webp" srcset="/assets/img/thumbs/transport-quada-na-lawecie-pabianice-400.webp 400w, /assets/img/thumbs/transport-quada-na-lawecie-pabianice-800.webp 800w" sizes="(max-width:699px) 50vw, 25vw"><img src="/assets/img/thumbs/transport-quada-na-lawecie-pabianice.jpg" alt="Transport quada na lawecie — Pomoc Drogowa Pabianice" width="800" height="450" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell" data-shot="4" data-full="/assets/img/awaryjna-wymiana-kola-na-miejscu-pabianice.jpg" aria-label="Powiększ zdjęcie: Awaryjna wymiana koła na miejscu — mobilny serwis Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/awaryjna-wymiana-kola-na-miejscu-pabianice-400.avif 400w, /assets/img/thumbs/awaryjna-wymiana-kola-na-miejscu-pabianice-800.avif 800w" sizes="(max-width:699px) 50vw, 25vw"><source type="image/webp" srcset="/assets/img/thumbs/awaryjna-wymiana-kola-na-miejscu-pabianice-400.webp 400w, /assets/img/thumbs/awaryjna-wymiana-kola-na-miejscu-pabianice-800.webp 800w" sizes="(max-width:699px) 50vw, 25vw"><img src="/assets/img/thumbs/awaryjna-wymiana-kola-na-miejscu-pabianice.jpg" alt="Awaryjna wymiana koła na miejscu — mobilny serwis Pabianice" width="800" height="450" loading="lazy" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell" data-shot="5" data-full="/assets/img/zolta-laweta-pomoc-drogowa-lukasz-rogowski-pabianice.jpg" aria-label="Powiększ zdjęcie: Żółta laweta Pomocy Drogowej Łukasz Rogowski z SUV-em na platformie, Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/zolta-laweta-pomoc-drogowa-lukasz-rogowski-pabianice-400.avif 400w, /assets/img/thumbs/zolta-laweta-pomoc-drogowa-lukasz-rogowski-pabianice-800.avif 800w" sizes="(max-width:699px) 50vw, 25vw"><source type="image/webp" srcset="/assets/img/thumbs/zolta-laweta-pomoc-drogowa-lukasz-rogowski-pabianice-400.webp 400w, /assets/img/thumbs/zolta-laweta-pomoc-drogowa-lukasz-rogowski-pabianice-800.webp 800w" sizes="(max-width:699px) 50vw, 25vw"><img src="/assets/img/thumbs/zolta-laweta-pomoc-drogowa-lukasz-rogowski-pabianice.jpg" alt="Żółta laweta Pomocy Drogowej Łukasz Rogowski z SUV-em na platformie, Pabianice" width="800" height="583" loading="lazy" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell" data-shot="6" data-full="/assets/img/booster-podlaczony-do-akumulatorow-autobusu-pabianice.jpg" aria-label="Powiększ zdjęcie: Urządzenie rozruchowe podłączone do akumulatorów autobusu — awaryjne odpalanie, Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/booster-podlaczony-do-akumulatorow-autobusu-pabianice-400.avif 400w, /assets/img/thumbs/booster-podlaczony-do-akumulatorow-autobusu-pabianice-800.avif 800w" sizes="(max-width:699px) 50vw, 25vw"><source type="image/webp" srcset="/assets/img/thumbs/booster-podlaczony-do-akumulatorow-autobusu-pabianice-400.webp 400w, /assets/img/thumbs/booster-podlaczony-do-akumulatorow-autobusu-pabianice-800.webp 800w" sizes="(max-width:699px) 50vw, 25vw"><img src="/assets/img/thumbs/booster-podlaczony-do-akumulatorow-autobusu-pabianice.jpg" alt="Urządzenie rozruchowe podłączone do akumulatorów autobusu — awaryjne odpalanie, Pabianice" width="800" height="450" loading="lazy" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell is-big" data-shot="7" data-full="/assets/img/holowanie-rozbitego-audi-po-kolizji-pabianice.jpg" aria-label="Powiększ zdjęcie: Żółta laweta Pomocy Drogowej Łukasz Rogowski z rozbitym SUV-em po kolizji, obok straż pożarna — Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/holowanie-rozbitego-audi-po-kolizji-pabianice-400.avif 400w, /assets/img/thumbs/holowanie-rozbitego-audi-po-kolizji-pabianice-800.avif 800w" sizes="(max-width:699px) 100vw, 50vw"><source type="image/webp" srcset="/assets/img/thumbs/holowanie-rozbitego-audi-po-kolizji-pabianice-400.webp 400w, /assets/img/thumbs/holowanie-rozbitego-audi-po-kolizji-pabianice-800.webp 800w" sizes="(max-width:699px) 100vw, 50vw"><img src="/assets/img/thumbs/holowanie-rozbitego-audi-po-kolizji-pabianice.jpg" alt="Żółta laweta Pomocy Drogowej Łukasz Rogowski z rozbitym SUV-em po kolizji, obok straż pożarna — Pabianice" width="800" height="450" loading="lazy" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell" data-shot="8" data-full="/assets/img/laweta-z-przyczepa-transport-ulica-pabianice.jpg" aria-label="Powiększ zdjęcie: Laweta z przyczepą w transporcie ulicą — Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/laweta-z-przyczepa-transport-ulica-pabianice-400.avif 400w, /assets/img/thumbs/laweta-z-przyczepa-transport-ulica-pabianice-800.avif 800w" sizes="(max-width:699px) 50vw, 25vw"><source type="image/webp" srcset="/assets/img/thumbs/laweta-z-przyczepa-transport-ulica-pabianice-400.webp 400w, /assets/img/thumbs/laweta-z-przyczepa-transport-ulica-pabianice-800.webp 800w" sizes="(max-width:699px) 50vw, 25vw"><img src="/assets/img/thumbs/laweta-z-przyczepa-transport-ulica-pabianice.jpg" alt="Laweta z przyczepą w transporcie ulicą — Pabianice" width="800" height="450" loading="lazy" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell" data-shot="9" data-full="/assets/img/holowanie-auta-po-awarii-z-osiedla-pabianice.jpg" aria-label="Powiększ zdjęcie: Laweta zabiera auto po awarii z osiedla — Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/holowanie-auta-po-awarii-z-osiedla-pabianice-400.avif 400w, /assets/img/thumbs/holowanie-auta-po-awarii-z-osiedla-pabianice-800.avif 800w" sizes="(max-width:699px) 50vw, 25vw"><source type="image/webp" srcset="/assets/img/thumbs/holowanie-auta-po-awarii-z-osiedla-pabianice-400.webp 400w, /assets/img/thumbs/holowanie-auta-po-awarii-z-osiedla-pabianice-800.webp 800w" sizes="(max-width:699px) 50vw, 25vw"><img src="/assets/img/thumbs/holowanie-auta-po-awarii-z-osiedla-pabianice.jpg" alt="Laweta zabiera auto po awarii z osiedla — Pabianice" width="800" height="450" loading="lazy" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell is-big" data-shot="10" data-full="/assets/img/holowanie-rozbitego-auta-laweta-noca-pabianice.jpg" aria-label="Powiększ zdjęcie: Holowanie rozbitego auta lawetą nocą po wypadku — pomoc drogowa 24h Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/holowanie-rozbitego-auta-laweta-noca-pabianice-400.avif 400w, /assets/img/thumbs/holowanie-rozbitego-auta-laweta-noca-pabianice-800.avif 800w" sizes="(max-width:699px) 100vw, 50vw"><source type="image/webp" srcset="/assets/img/thumbs/holowanie-rozbitego-auta-laweta-noca-pabianice-400.webp 400w, /assets/img/thumbs/holowanie-rozbitego-auta-laweta-noca-pabianice-800.webp 800w" sizes="(max-width:699px) 100vw, 50vw"><img src="/assets/img/thumbs/holowanie-rozbitego-auta-laweta-noca-pabianice.jpg" alt="Holowanie rozbitego auta lawetą nocą po wypadku — pomoc drogowa 24h Pabianice" width="800" height="450" loading="lazy" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell is-big" data-shot="11" data-full="/assets/img/transport-dwoch-aut-laweta-z-przyczepa-pabianice.jpg" aria-label="Powiększ zdjęcie: Transport dwóch samochodów lawetą z przyczepą — Pomoc Drogowa Łukasz Rogowski, Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/transport-dwoch-aut-laweta-z-przyczepa-pabianice-400.avif 400w, /assets/img/thumbs/transport-dwoch-aut-laweta-z-przyczepa-pabianice-800.avif 800w" sizes="(max-width:699px) 100vw, 50vw"><source type="image/webp" srcset="/assets/img/thumbs/transport-dwoch-aut-laweta-z-przyczepa-pabianice-400.webp 400w, /assets/img/thumbs/transport-dwoch-aut-laweta-z-przyczepa-pabianice-800.webp 800w" sizes="(max-width:699px) 100vw, 50vw"><img src="/assets/img/thumbs/transport-dwoch-aut-laweta-z-przyczepa-pabianice.jpg" alt="Transport dwóch samochodów lawetą z przyczepą — Pomoc Drogowa Łukasz Rogowski, Pabianice" width="800" height="450" loading="lazy" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell" data-shot="12" data-full="/assets/img/naprawa-przebitej-opony-na-miejscu-pabianice.jpg" aria-label="Powiększ zdjęcie: Naprawa przebitej opony na miejscu — mobilny serwis Pomoc Drogowa Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/naprawa-przebitej-opony-na-miejscu-pabianice-400.avif 400w, /assets/img/thumbs/naprawa-przebitej-opony-na-miejscu-pabianice-800.avif 800w" sizes="(max-width:699px) 50vw, 25vw"><source type="image/webp" srcset="/assets/img/thumbs/naprawa-przebitej-opony-na-miejscu-pabianice-400.webp 400w, /assets/img/thumbs/naprawa-przebitej-opony-na-miejscu-pabianice-800.webp 800w" sizes="(max-width:699px) 50vw, 25vw"><img src="/assets/img/thumbs/naprawa-przebitej-opony-na-miejscu-pabianice.jpg" alt="Naprawa przebitej opony na miejscu — mobilny serwis Pomoc Drogowa Pabianice" width="800" height="450" loading="lazy" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell" data-shot="13" data-full="/assets/img/rozruch-autobusu-boosterem-pomoc-drogowa-pabianice.jpg" aria-label="Powiększ zdjęcie: Awaryjny rozruch autobusu z urządzenia rozruchowego — pomoc drogowa Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/rozruch-autobusu-boosterem-pomoc-drogowa-pabianice-400.avif 400w, /assets/img/thumbs/rozruch-autobusu-boosterem-pomoc-drogowa-pabianice-800.avif 800w" sizes="(max-width:699px) 50vw, 25vw"><source type="image/webp" srcset="/assets/img/thumbs/rozruch-autobusu-boosterem-pomoc-drogowa-pabianice-400.webp 400w, /assets/img/thumbs/rozruch-autobusu-boosterem-pomoc-drogowa-pabianice-800.webp 800w" sizes="(max-width:699px) 50vw, 25vw"><img src="/assets/img/thumbs/rozruch-autobusu-boosterem-pomoc-drogowa-pabianice.jpg" alt="Awaryjny rozruch autobusu z urządzenia rozruchowego — pomoc drogowa Pabianice" width="800" height="450" loading="lazy" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell is-big" data-shot="14" data-full="/assets/img/awaria-auta-droga-ekspresowa-laweta-pabianice.jpg" aria-label="Powiększ zdjęcie: Żółta laweta przy zepsutym aucie na poboczu drogi ekspresowej — pomoc drogowa Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/awaria-auta-droga-ekspresowa-laweta-pabianice-400.avif 400w, /assets/img/thumbs/awaria-auta-droga-ekspresowa-laweta-pabianice-800.avif 800w" sizes="(max-width:699px) 100vw, 50vw"><source type="image/webp" srcset="/assets/img/thumbs/awaria-auta-droga-ekspresowa-laweta-pabianice-400.webp 400w, /assets/img/thumbs/awaria-auta-droga-ekspresowa-laweta-pabianice-800.webp 800w" sizes="(max-width:699px) 100vw, 50vw"><img src="/assets/img/thumbs/awaria-auta-droga-ekspresowa-laweta-pabianice.jpg" alt="Żółta laweta przy zepsutym aucie na poboczu drogi ekspresowej — pomoc drogowa Pabianice" width="800" height="450" loading="lazy" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell" data-shot="15" data-full="/assets/img/mobilny-serwis-samochodowy-van-pabianice.jpg" aria-label="Powiększ zdjęcie: Van mobilnego serwisu samochodowego Pomoc Drogowa Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/mobilny-serwis-samochodowy-van-pabianice-400.avif 400w, /assets/img/thumbs/mobilny-serwis-samochodowy-van-pabianice-800.avif 800w" sizes="(max-width:699px) 50vw, 25vw"><source type="image/webp" srcset="/assets/img/thumbs/mobilny-serwis-samochodowy-van-pabianice-400.webp 400w, /assets/img/thumbs/mobilny-serwis-samochodowy-van-pabianice-800.webp 800w" sizes="(max-width:699px) 50vw, 25vw"><img src="/assets/img/thumbs/mobilny-serwis-samochodowy-van-pabianice.jpg" alt="Van mobilnego serwisu samochodowego Pomoc Drogowa Pabianice" width="800" height="409" loading="lazy" decoding="async"></picture>
      </button>
      <button type="button" class="gal-cell" data-shot="16" data-full="/assets/img/van-pomocy-drogowej-przy-autobusie-pabianice.jpg" aria-label="Powiększ zdjęcie: Van Pomocy Drogowej przy autobusie podczas awaryjnego odpalania — Pabianice">
        <picture style="display:contents"><source type="image/avif" srcset="/assets/img/thumbs/van-pomocy-drogowej-przy-autobusie-pabianice-400.avif 400w, /assets/img/thumbs/van-pomocy-drogowej-przy-autobusie-pabianice-800.avif 800w" sizes="(max-width:699px) 50vw, 25vw"><source type="image/webp" srcset="/assets/img/thumbs/van-pomocy-drogowej-przy-autobusie-pabianice-400.webp 400w, /assets/img/thumbs/van-pomocy-drogowej-przy-autobusie-pabianice-800.webp 800w" sizes="(max-width:699px) 50vw, 25vw"><img src="/assets/img/thumbs/van-pomocy-drogowej-przy-autobusie-pabianice.jpg" alt="Van Pomocy Drogowej przy autobusie podczas awaryjnego odpalania — Pabianice" width="800" height="450" loading="lazy" decoding="async"></picture>
      </button>
<!-- GALLERY:END -->
    </div>
    <div style="display:flex;justify-content:center;margin-top:32px" data-more-wrap hidden>
      <button type="button" data-more class="hov-brand hov-lift-flat press" style="all:unset;cursor:pointer;border:2px solid #f5c518;color:#f5c518;font-weight:800;font-size:17px;padding:14px 28px;transition:background-color .2s,color .2s,transform .2s cubic-bezier(.2,.7,.2,1)">Zobacz więcej zdjęć (<span data-more-count>0</span>)</button>
    </div>
  </section>

  <!-- LIGHTBOX -->
  <div class="lb" data-lightbox role="dialog" aria-modal="true" aria-label="Podgląd zdjęcia" tabindex="-1">
    <img data-lbimg src="" alt="" style="display:none">
    <button type="button" data-lbprev aria-label="Poprzednie" class="lb-btn lb-prev hov-brand"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="square" aria-hidden="true"><path d="M15 5l-7 7 7 7"/></svg></button>
    <button type="button" data-lbnext aria-label="Następne" class="lb-btn lb-next hov-brand"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="square" aria-hidden="true"><path d="M9 5l7 7-7 7"/></svg></button>
    <button type="button" data-lbclose aria-label="Zamknij" class="lb-btn lb-close hov-brand"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="square" aria-hidden="true"><path d="M5 5l14 14M19 5L5 19"/></svg></button>
    <div data-lbpos style="position:absolute;left:50%;bottom:20px;transform:translateX(-50%);background:#111;color:#ccc;font-size:14px;font-weight:700;padding:6px 12px"></div>
  </div>
<?php
include __DIR__ . '/partials/cta.php';
include __DIR__ . '/partials/footer.php';
